# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

output: prefixed

includes:
  identity:
    taskfile: ./services/identity/Taskfile.yml
    dir: ./services/identity

  catalog:
    taskfile: ./services/catalog/Taskfile.yml
    dir: ./services/catalog

  api-gateway:
    taskfile: ./services/api-gateway/Taskfile.yml
    dir: ./services/api-gateway

tasks:
  default:
    cmds:
      - task --list-all

  run-dev-all:
    desc: "run all dev microservices"
    deps:
      - identity:run-dev
      - catalog:run-dev
      - api-gateway:run-dev

  grpc-gen-all:
    desc: "generace grpc code for all microservices"
    deps:
      - identity:grpc-gen
      - catalog:grpc-gen
      - api-gateway:grpc-gen
