// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, parent_id)
VALUES ($1, $2)
RETURNING id, name, parent_id, created_at
`

type CreateCategoryParams struct {
	Name     string
	ParentID pgtype.Int4
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.ParentID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
	)
	return i, err
}
