// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, description, price, attributes, creator_id, category_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, description, price, attributes, status, creator_id, category_id, deleted_at, updated_at, created_at
`

type CreateProductParams struct {
	Name        string
	Description string
	Price       pgtype.Numeric
	Attributes  []byte
	CreatorID   pgtype.UUID
	CategoryID  int32
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Attributes,
		arg.CreatorID,
		arg.CategoryID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Attributes,
		&i.Status,
		&i.CreatorID,
		&i.CategoryID,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, description, price, attributes, status, creator_id, category_id, deleted_at, updated_at, created_at FROM products WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Attributes,
		&i.Status,
		&i.CreatorID,
		&i.CategoryID,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getProductsByCategory = `-- name: GetProductsByCategory :many
SELECT p.id, p.name, p.description, p.price, p.attributes, p.status, p.creator_id, p.category_id, p.deleted_at, p.updated_at, p.created_at
FROM products p
WHERE p.category_id = $1 AND p.deleted_at IS NULL
`

func (q *Queries) GetProductsByCategory(ctx context.Context, categoryID int32) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProductsByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Attributes,
			&i.Status,
			&i.CreatorID,
			&i.CategoryID,
			&i.DeletedAt,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsByCreator = `-- name: GetProductsByCreator :many
SELECT id, name, description, price, attributes, status, creator_id, category_id, deleted_at, updated_at, created_at FROM products WHERE creator_id = $1
`

func (q *Queries) GetProductsByCreator(ctx context.Context, creatorID pgtype.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProductsByCreator, creatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Attributes,
			&i.Status,
			&i.CreatorID,
			&i.CategoryID,
			&i.DeletedAt,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
