# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  GREETING: Hello, world!

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  build:
    cmds:
      - go build -o bin/ ./cmd/identity/main.go

  goose-create:*:
    vars:
      NAME: '{{index .MATCH 0}}'
    cmds:
      - goose create -dir ./sql/migrations {{.NAME}} sql

  goose-up:
    cmds:
      - goose up -dir ./sql/migrations

  goose-down:
    cmds:
      - goose down -dir ./sql/migrations

  sqlc:
    cmds:
      - sqlc generate

  grpc-gen:
    cmds:
      - protoc --go_out=internal/ --go-grpc_out=internal/ internal/grpc/v1/*.proto
