# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  run:
    cmds:
      - go run ./cmd/catalog/main.go

  run-dev:
    cmds:
      - docker compose -f ./docker-compose.dev.yaml up -d
      - task: run

  build:
    cmds:
      - go build -o bin/ ./cmd/catalog/main.go

  goose-create:*:
    vars:
      NAME: '{{index .MATCH 0}}'
    cmds:
      - goose create -dir ./sql/migrations {{.NAME}} sql

  goose-up:
    cmds:
      - goose up -dir ./sql/migrations

  goose-down:
    cmds:
      - goose down -dir ./sql/migrations

  sqlc:
    cmds:
      - sqlc generate

  grpc-gen:
    cmds:
      - >
        protoc
        -I=../../api/proto
        --go_out=internal/grpc
        --go_opt=paths=source_relative
        --go-grpc_out=internal/grpc
        --go-grpc_opt=paths=source_relative
        ../../api/proto/catalog/v1/*.proto

  test:
    cmds:
      - go test ./...

  fmt:
    desc: Format Go files
    cmds:
      - goimports -w -local catalog/ .
      - gofmt -w .

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./...

  check:
    desc: Run all checks
    deps: [fmt, vet, lint]

  pre-commit:
    desc: Run pre-commit checks
    cmds:
      - task: fmt
      - task: vet
      - task: lint
      - git add -u
