// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	ID        pgtype.UUID
	Token     string
	UserID    pgtype.UUID
	ExpiredAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	Username  string
	Email     string
	Password  string
	UpdatedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}
