// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (token, user_id, expired_at)
VALUES ($1, $2, $3)
RETURNING id, token, user_id, expired_at, created_at
`

type CreateRefreshTokenParams struct {
	Token     string
	UserID    pgtype.UUID
	ExpiredAt pgtype.Timestamptz
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.Token, arg.UserID, arg.ExpiredAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.ExpiredAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens WHERe token = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteRefreshToken, token)
	return err
}

const existRefreshTokenByUser = `-- name: ExistRefreshTokenByUser :one
SELECT EXISTS (
    SELECT 1 FROM refresh_tokens
    WHERE user_id = $1 AND token = $2
) as exists
`

type ExistRefreshTokenByUserParams struct {
	UserID pgtype.UUID
	Token  string
}

func (q *Queries) ExistRefreshTokenByUser(ctx context.Context, arg ExistRefreshTokenByUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, existRefreshTokenByUser, arg.UserID, arg.Token)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByRefreshToken = `-- name: GetUserByRefreshToken :one
SELECT u.id, u.username, u.email, u.password, u.created_at
FROM users u
JOIN refresh_tokens rt ON rt.user_id = u.id
WHERE rt.token = $1
  AND rt.expired_at > NOW()
LIMIT 1
`

func (q *Queries) GetUserByRefreshToken(ctx context.Context, token string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByRefreshToken, token)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}
