// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteRefreshToken(ctx context.Context, token string) error
	ExistRefreshTokenByUser(ctx context.Context, arg ExistRefreshTokenByUserParams) (bool, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByRefreshToken(ctx context.Context, token string) (User, error)
}

var _ Querier = (*Queries)(nil)
