// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"identity/internal/dbgen"

	"github.com/jackc/pgx/v5/pgtype"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) CreateUser(ctx context.Context, arg dbgen.CreateUserParams) (dbgen.User, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 dbgen.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dbgen.CreateUserParams) (dbgen.User, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dbgen.CreateUserParams) dbgen.User); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(dbgen.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dbgen.CreateUserParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg dbgen.CreateUserParams
func (_e *MockUserRepository_Expecter) CreateUser(ctx any, arg any) *MockUserRepository_CreateUser_Call {
	return &MockUserRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, arg)}
}

func (_c *MockUserRepository_CreateUser_Call) Run(run func(ctx context.Context, arg dbgen.CreateUserParams)) *MockUserRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dbgen.CreateUserParams
		if args[1] != nil {
			arg1 = args[1].(dbgen.CreateUserParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_CreateUser_Call) Return(user dbgen.User, err error) *MockUserRepository_CreateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_CreateUser_Call) RunAndReturn(run func(ctx context.Context, arg dbgen.CreateUserParams) (dbgen.User, error)) *MockUserRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetUser(ctx context.Context, id pgtype.UUID) (dbgen.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 dbgen.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (dbgen.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgtype.UUID) dbgen.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(dbgen.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUserRepository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id pgtype.UUID
func (_e *MockUserRepository_Expecter) GetUser(ctx any, id any) *MockUserRepository_GetUser_Call {
	return &MockUserRepository_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *MockUserRepository_GetUser_Call) Run(run func(ctx context.Context, id pgtype.UUID)) *MockUserRepository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgtype.UUID
		if args[1] != nil {
			arg1 = args[1].(pgtype.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetUser_Call) Return(user dbgen.User, err error) *MockUserRepository_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetUser_Call) RunAndReturn(run func(ctx context.Context, id pgtype.UUID) (dbgen.User, error)) *MockUserRepository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetUserByEmail(ctx context.Context, email string) (dbgen.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 dbgen.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (dbgen.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) dbgen.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(dbgen.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockUserRepository_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepository_Expecter) GetUserByEmail(ctx any, email any) *MockUserRepository_GetUserByEmail_Call {
	return &MockUserRepository_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockUserRepository_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepository_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetUserByEmail_Call) Return(user dbgen.User, err error) *MockUserRepository_GetUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (dbgen.User, error)) *MockUserRepository_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefreshTokenRepository creates a new instance of MockRefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRefreshTokenRepository is an autogenerated mock type for the RefreshTokenRepository type
type MockRefreshTokenRepository struct {
	mock.Mock
}

type MockRefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepository_Expecter {
	return &MockRefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// CreateRefreshToken provides a mock function for the type MockRefreshTokenRepository
func (_mock *MockRefreshTokenRepository) CreateRefreshToken(ctx context.Context, arg dbgen.CreateRefreshTokenParams) (dbgen.RefreshToken, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateRefreshToken")
	}

	var r0 dbgen.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dbgen.CreateRefreshTokenParams) (dbgen.RefreshToken, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dbgen.CreateRefreshTokenParams) dbgen.RefreshToken); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(dbgen.RefreshToken)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dbgen.CreateRefreshTokenParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRefreshTokenRepository_CreateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRefreshToken'
type MockRefreshTokenRepository_CreateRefreshToken_Call struct {
	*mock.Call
}

// CreateRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - arg dbgen.CreateRefreshTokenParams
func (_e *MockRefreshTokenRepository_Expecter) CreateRefreshToken(ctx any, arg any) *MockRefreshTokenRepository_CreateRefreshToken_Call {
	return &MockRefreshTokenRepository_CreateRefreshToken_Call{Call: _e.mock.On("CreateRefreshToken", ctx, arg)}
}

func (_c *MockRefreshTokenRepository_CreateRefreshToken_Call) Run(run func(ctx context.Context, arg dbgen.CreateRefreshTokenParams)) *MockRefreshTokenRepository_CreateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dbgen.CreateRefreshTokenParams
		if args[1] != nil {
			arg1 = args[1].(dbgen.CreateRefreshTokenParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepository_CreateRefreshToken_Call) Return(refreshToken dbgen.RefreshToken, err error) *MockRefreshTokenRepository_CreateRefreshToken_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *MockRefreshTokenRepository_CreateRefreshToken_Call) RunAndReturn(run func(ctx context.Context, arg dbgen.CreateRefreshTokenParams) (dbgen.RefreshToken, error)) *MockRefreshTokenRepository_CreateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRefreshToken provides a mock function for the type MockRefreshTokenRepository
func (_mock *MockRefreshTokenRepository) DeleteRefreshToken(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefreshTokenRepository_DeleteRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRefreshToken'
type MockRefreshTokenRepository_DeleteRefreshToken_Call struct {
	*mock.Call
}

// DeleteRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockRefreshTokenRepository_Expecter) DeleteRefreshToken(ctx any, token any) *MockRefreshTokenRepository_DeleteRefreshToken_Call {
	return &MockRefreshTokenRepository_DeleteRefreshToken_Call{Call: _e.mock.On("DeleteRefreshToken", ctx, token)}
}

func (_c *MockRefreshTokenRepository_DeleteRefreshToken_Call) Run(run func(ctx context.Context, token string)) *MockRefreshTokenRepository_DeleteRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteRefreshToken_Call) Return(err error) *MockRefreshTokenRepository_DeleteRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteRefreshToken_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockRefreshTokenRepository_DeleteRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// ExistRefreshTokenByUser provides a mock function for the type MockRefreshTokenRepository
func (_mock *MockRefreshTokenRepository) ExistRefreshTokenByUser(ctx context.Context, arg dbgen.ExistRefreshTokenByUserParams) (bool, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ExistRefreshTokenByUser")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dbgen.ExistRefreshTokenByUserParams) (bool, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dbgen.ExistRefreshTokenByUserParams) bool); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dbgen.ExistRefreshTokenByUserParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRefreshTokenRepository_ExistRefreshTokenByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistRefreshTokenByUser'
type MockRefreshTokenRepository_ExistRefreshTokenByUser_Call struct {
	*mock.Call
}

// ExistRefreshTokenByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg dbgen.ExistRefreshTokenByUserParams
func (_e *MockRefreshTokenRepository_Expecter) ExistRefreshTokenByUser(ctx any, arg any) *MockRefreshTokenRepository_ExistRefreshTokenByUser_Call {
	return &MockRefreshTokenRepository_ExistRefreshTokenByUser_Call{Call: _e.mock.On("ExistRefreshTokenByUser", ctx, arg)}
}

func (_c *MockRefreshTokenRepository_ExistRefreshTokenByUser_Call) Run(run func(ctx context.Context, arg dbgen.ExistRefreshTokenByUserParams)) *MockRefreshTokenRepository_ExistRefreshTokenByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dbgen.ExistRefreshTokenByUserParams
		if args[1] != nil {
			arg1 = args[1].(dbgen.ExistRefreshTokenByUserParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepository_ExistRefreshTokenByUser_Call) Return(b bool, err error) *MockRefreshTokenRepository_ExistRefreshTokenByUser_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRefreshTokenRepository_ExistRefreshTokenByUser_Call) RunAndReturn(run func(ctx context.Context, arg dbgen.ExistRefreshTokenByUserParams) (bool, error)) *MockRefreshTokenRepository_ExistRefreshTokenByUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByRefreshToken provides a mock function for the type MockRefreshTokenRepository
func (_mock *MockRefreshTokenRepository) GetUserByRefreshToken(ctx context.Context, token string) (dbgen.User, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByRefreshToken")
	}

	var r0 dbgen.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (dbgen.User, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) dbgen.User); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(dbgen.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRefreshTokenRepository_GetUserByRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByRefreshToken'
type MockRefreshTokenRepository_GetUserByRefreshToken_Call struct {
	*mock.Call
}

// GetUserByRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockRefreshTokenRepository_Expecter) GetUserByRefreshToken(ctx any, token any) *MockRefreshTokenRepository_GetUserByRefreshToken_Call {
	return &MockRefreshTokenRepository_GetUserByRefreshToken_Call{Call: _e.mock.On("GetUserByRefreshToken", ctx, token)}
}

func (_c *MockRefreshTokenRepository_GetUserByRefreshToken_Call) Run(run func(ctx context.Context, token string)) *MockRefreshTokenRepository_GetUserByRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepository_GetUserByRefreshToken_Call) Return(user dbgen.User, err error) *MockRefreshTokenRepository_GetUserByRefreshToken_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRefreshTokenRepository_GetUserByRefreshToken_Call) RunAndReturn(run func(ctx context.Context, token string) (dbgen.User, error)) *MockRefreshTokenRepository_GetUserByRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
