// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"catalog/internal/db"
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCategoryRepository creates a new instance of MockCategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategoryRepository {
	mock := &MockCategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCategoryRepository is an autogenerated mock type for the CategoryRepository type
type MockCategoryRepository struct {
	mock.Mock
}

type MockCategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategoryRepository) EXPECT() *MockCategoryRepository_Expecter {
	return &MockCategoryRepository_Expecter{mock: &_m.Mock}
}

// CreateCategory provides a mock function for the type MockCategoryRepository
func (_mock *MockCategoryRepository) CreateCategory(ctx context.Context, arg db.CreateCategoryParams) (db.Category, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateCategory")
	}

	var r0 db.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateCategoryParams) (db.Category, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateCategoryParams) db.Category); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Category)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.CreateCategoryParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryRepository_CreateCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCategory'
type MockCategoryRepository_CreateCategory_Call struct {
	*mock.Call
}

// CreateCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateCategoryParams
func (_e *MockCategoryRepository_Expecter) CreateCategory(ctx any, arg any) *MockCategoryRepository_CreateCategory_Call {
	return &MockCategoryRepository_CreateCategory_Call{Call: _e.mock.On("CreateCategory", ctx, arg)}
}

func (_c *MockCategoryRepository_CreateCategory_Call) Run(run func(ctx context.Context, arg db.CreateCategoryParams)) *MockCategoryRepository_CreateCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.CreateCategoryParams
		if args[1] != nil {
			arg1 = args[1].(db.CreateCategoryParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategoryRepository_CreateCategory_Call) Return(category db.Category, err error) *MockCategoryRepository_CreateCategory_Call {
	_c.Call.Return(category, err)
	return _c
}

func (_c *MockCategoryRepository_CreateCategory_Call) RunAndReturn(run func(ctx context.Context, arg db.CreateCategoryParams) (db.Category, error)) *MockCategoryRepository_CreateCategory_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductRepository creates a new instance of MockProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductRepository {
	mock := &MockProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProductRepository is an autogenerated mock type for the ProductRepository type
type MockProductRepository struct {
	mock.Mock
}

type MockProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductRepository) EXPECT() *MockProductRepository_Expecter {
	return &MockProductRepository_Expecter{mock: &_m.Mock}
}

// CreateProduct provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) CreateProduct(ctx context.Context, arg db.CreateProductParams) (db.Product, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 db.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateProductParams) (db.Product, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateProductParams) db.Product); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Product)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.CreateProductParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductRepository_CreateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProduct'
type MockProductRepository_CreateProduct_Call struct {
	*mock.Call
}

// CreateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateProductParams
func (_e *MockProductRepository_Expecter) CreateProduct(ctx any, arg any) *MockProductRepository_CreateProduct_Call {
	return &MockProductRepository_CreateProduct_Call{Call: _e.mock.On("CreateProduct", ctx, arg)}
}

func (_c *MockProductRepository_CreateProduct_Call) Run(run func(ctx context.Context, arg db.CreateProductParams)) *MockProductRepository_CreateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.CreateProductParams
		if args[1] != nil {
			arg1 = args[1].(db.CreateProductParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductRepository_CreateProduct_Call) Return(product db.Product, err error) *MockProductRepository_CreateProduct_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockProductRepository_CreateProduct_Call) RunAndReturn(run func(ctx context.Context, arg db.CreateProductParams) (db.Product, error)) *MockProductRepository_CreateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// GetProduct provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) GetProduct(ctx context.Context, id pgtype.UUID) (db.Product, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProduct")
	}

	var r0 db.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (db.Product, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgtype.UUID) db.Product); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(db.Product)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductRepository_GetProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProduct'
type MockProductRepository_GetProduct_Call struct {
	*mock.Call
}

// GetProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - id pgtype.UUID
func (_e *MockProductRepository_Expecter) GetProduct(ctx any, id any) *MockProductRepository_GetProduct_Call {
	return &MockProductRepository_GetProduct_Call{Call: _e.mock.On("GetProduct", ctx, id)}
}

func (_c *MockProductRepository_GetProduct_Call) Run(run func(ctx context.Context, id pgtype.UUID)) *MockProductRepository_GetProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgtype.UUID
		if args[1] != nil {
			arg1 = args[1].(pgtype.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductRepository_GetProduct_Call) Return(product db.Product, err error) *MockProductRepository_GetProduct_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockProductRepository_GetProduct_Call) RunAndReturn(run func(ctx context.Context, id pgtype.UUID) (db.Product, error)) *MockProductRepository_GetProduct_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductsByCategory provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) GetProductsByCategory(ctx context.Context, categoryID int32) ([]db.Product, error) {
	ret := _mock.Called(ctx, categoryID)

	if len(ret) == 0 {
		panic("no return value specified for GetProductsByCategory")
	}

	var r0 []db.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) ([]db.Product, error)); ok {
		return returnFunc(ctx, categoryID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) []db.Product); ok {
		r0 = returnFunc(ctx, categoryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, categoryID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductRepository_GetProductsByCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductsByCategory'
type MockProductRepository_GetProductsByCategory_Call struct {
	*mock.Call
}

// GetProductsByCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - categoryID int32
func (_e *MockProductRepository_Expecter) GetProductsByCategory(ctx any, categoryID any) *MockProductRepository_GetProductsByCategory_Call {
	return &MockProductRepository_GetProductsByCategory_Call{Call: _e.mock.On("GetProductsByCategory", ctx, categoryID)}
}

func (_c *MockProductRepository_GetProductsByCategory_Call) Run(run func(ctx context.Context, categoryID int32)) *MockProductRepository_GetProductsByCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductRepository_GetProductsByCategory_Call) Return(products []db.Product, err error) *MockProductRepository_GetProductsByCategory_Call {
	_c.Call.Return(products, err)
	return _c
}

func (_c *MockProductRepository_GetProductsByCategory_Call) RunAndReturn(run func(ctx context.Context, categoryID int32) ([]db.Product, error)) *MockProductRepository_GetProductsByCategory_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductsByCreator provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) GetProductsByCreator(ctx context.Context, creatorID pgtype.UUID) ([]db.Product, error) {
	ret := _mock.Called(ctx, creatorID)

	if len(ret) == 0 {
		panic("no return value specified for GetProductsByCreator")
	}

	var r0 []db.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgtype.UUID) ([]db.Product, error)); ok {
		return returnFunc(ctx, creatorID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgtype.UUID) []db.Product); ok {
		r0 = returnFunc(ctx, creatorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = returnFunc(ctx, creatorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductRepository_GetProductsByCreator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductsByCreator'
type MockProductRepository_GetProductsByCreator_Call struct {
	*mock.Call
}

// GetProductsByCreator is a helper method to define mock.On call
//   - ctx context.Context
//   - creatorID pgtype.UUID
func (_e *MockProductRepository_Expecter) GetProductsByCreator(ctx any, creatorID any) *MockProductRepository_GetProductsByCreator_Call {
	return &MockProductRepository_GetProductsByCreator_Call{Call: _e.mock.On("GetProductsByCreator", ctx, creatorID)}
}

func (_c *MockProductRepository_GetProductsByCreator_Call) Run(run func(ctx context.Context, creatorID pgtype.UUID)) *MockProductRepository_GetProductsByCreator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgtype.UUID
		if args[1] != nil {
			arg1 = args[1].(pgtype.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductRepository_GetProductsByCreator_Call) Return(products []db.Product, err error) *MockProductRepository_GetProductsByCreator_Call {
	_c.Call.Return(products, err)
	return _c
}

func (_c *MockProductRepository_GetProductsByCreator_Call) RunAndReturn(run func(ctx context.Context, creatorID pgtype.UUID) ([]db.Product, error)) *MockProductRepository_GetProductsByCreator_Call {
	_c.Call.Return(run)
	return _c
}
